# title: Linus Aspelin

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://aspelin.org" # the base hostname & protocol for your site

github_username:  slayersvamp

# Build settings
markdown: kramdown
